# Generated by Django 4.1.2 on 2022-11-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_app', '0007_uploadimgmodel_square_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='square_number',
        ),
    ]
