# Generated by Django 4.1.2 on 2022-11-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_app', '0009_remove_uploadimgmodel_result1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='title',
        ),
    ]
