# Generated by Django 4.1.2 on 2022-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyStone_app', '0002_uploadimgmodel_delete_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
