# Generated by Django 4.1.2 on 2022-11-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyStone_app', '0008_remove_uploadimgmodel_square_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result10',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result11',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result12',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result13',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result2',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result3',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result4',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result5',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result6',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result7',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result8',
        ),
        migrations.RemoveField(
            model_name='uploadimgmodel',
            name='result9',
        ),
    ]
